# Generated by Django 6.0.6 on 2026-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state_location',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
