# Generated by Django 6.0.6 on 2026-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=32, null=True)),
                ('assistant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=64, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=32, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('lead_score', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-call_date', '-created_at'],
            },
        ),
    ]
