# Generated by Django 6.0 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['-call_date'], name='call_record_call_da_a57646_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['outcome'], name='call_record_outcome_17acc9_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['assistant_name'], name='call_record_assista_d0bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['caller_name'], name='call_record_caller__60a036_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['-created_at'], name='call_record_created_d12e0d_idx'),
        ),
    ]
